# Autogenerated wrapper script for leiden_jll for x86_64-linux-gnu
export libleiden

using igraph_jll
JLLWrappers.@generate_wrapper_header("leiden")
JLLWrappers.@declare_library_product(libleiden, "libleiden.so")
function __init__()
    JLLWrappers.@generate_init_header(igraph_jll)
    JLLWrappers.@init_library_product(
        libleiden,
        "lib/libleiden.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
